WeatherForecast/WeatherForecast/Controllers/DayForecastController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeatherForecast.Models;
using WeatherForecast.Manager;
using System.Threading.Tasks;

namespace WeatherForecast.Controllers
{
    public class DayForecastController : AsyncController
    {
        private IDayManager dayManager;

        public DayForecastController(IDayManager manager)
        {
            dayManager = manager;
        }

        // GET: /DayForecast/Index
        public ActionResult Index()
        {
            return View();
        }

        // GET: /DayForecast/SearchForecast
        public async Task<ActionResult> SearchForecast(string city)
        {
            DayModel list = new DayModel(dayManager);
            return View(await list.SearchForecast(city));
        }
    }
}

WeatherForecast/WeatherForecast/Controllers/WeekForecastController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WeatherForecast.Models;
using WeatherForecast.Manager;
using System.Threading.Tasks;

namespace WeatherForecast.Controllers
{
    public class WeekForecastController : Controller
    {
        private IWeekManager weekManager;

        public WeekForecastController(IWeekManager manager)
        {
            weekManager = manager;
        }

        // GET: /WeekForecast/Index
        public ActionResult Index()
        {
            return View();
        }

        //GET: /WeekForecast/SearchForecast
        public async Task<ActionResult> SearchForecast(string city, int count)
        {
            WeekModel list = new WeekModel(weekManager);
            return View(await list.SearchForecast(count, city)); 
        }
    }
}

WeatherForecast/WeatherForecast/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                </button>
                @Html.ActionLink("Search weather forecast", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                            Kiev
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("for one day", "SearchForecast", "DayForecast", new { city = "Kiev", count = 8 }, null)</li>
                            <li>@Html.ActionLink("for a three days", "SearchForecast", "WeekForecast", new { city = "Kiev", count = 3 }, null)</li>
                            <li>@Html.ActionLink("for a week", "SearchForecast", "WeekForecast", new { city = "Kiev", count = 7 }, null)</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                            Lviv
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("for one day", "SearchForecast", "DayForecast", new { city = "Lviv", count = 8 }, null)</li>
                            <li>@Html.ActionLink("for a three days", "SearchForecast", "WeekForecast", new { city = "Lviv", count = 3 }, null)</li>
                            <li>@Html.ActionLink("for a week", "SearchForecast", "WeekForecast", new { city = "Lviv", count = 7 }, null)</li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                            Kharkiv
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("for one day", "SearchForecast", "DayForecast", new { city = "Kharkiv", count = 8 }, null)</li>
                            <li>@Html.ActionLink("for a three days", "SearchForecast", "WeekForecast", new { city = "Kharkiv", count = 3 }, null)</li>
                            <li>@Html.ActionLink("for a week", "SearchForecast", "WeekForecast", new { city = "Kharkiv", count = 7 }, null)</li>
                        </ul>
                    </li>  
                    <li class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                            Dnipropetrovsk
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("for one day", "SearchForecast", "DayForecast", new { city = "Dnipropetrovsk", count = 8 }, null)</li>
                            <li>@Html.ActionLink("for a three days", "SearchForecast", "WeekForecast", new { city = "Dnipropetrovsk", count = 3 }, null)</li>
                            <li>@Html.ActionLink("for a week", "SearchForecast", "WeekForecast", new { city = "Dnipropetrovsk", count = 7 }, null)</li>
                        </ul>
                    </li> 
                    <li class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                            Odessa
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("for one day", "SearchForecast", "DayForecast", new { city = "Odessa", count = 8 }, null)</li>
                            <li>@Html.ActionLink("for a three days", "SearchForecast", "WeekForecast", new { city = "Odessa", count = 3 }, null)</li>
                            <li>@Html.ActionLink("for a week", "SearchForecast", "WeekForecast", new { city = "Odessa", count = 7 }, null)</li>
                        </ul>
                    </li> 
                    <li class="dropdown">
                        <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown">
                            Favourites
                            <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Edit favourites", "Favourites", "Home")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Statistics", "Statistics", "Home")</li>                   
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>